version: '3.8'

services:
  3wc-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 3wc-web-dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ['pnpm', 'run', 'dev', '--host']
