version: '3.8'

services:
  3wc-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3wc-web
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - LETSENCRYPT_DNS=cloudflare
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
